version: 1.2.0.{build}
configuration:
    Release

assembly_info:
    patch: true
    file: AssemblyInfo.*
    assembly_version: "{version}"
    assembly_file_version: "{version}"
    assembly_informational_version: "{version}"

build:
    project: Wox.sln

after_test:
    - ps: .\deploy\nuget\pack.ps1
    - cmd: .\deploy\UpdateGenerator\build.bat

artifacts:
    - path: Output\Release
      name: release-binary 

    - path: Output\Update
      name: update-binary
