version: 1.1.1.{build}

configuration:
    Release

assembly_info:
    patch: true
    file: AssemblyInfo.*
    assembly_version: "{version}"
    assembly_file_version: "{version}"
    assembly_informational_version: "{version}"

build:
    project: Wox.sln

after_test:
    - ps: .\deploy\nuget\pack.ps1
    - ps: .\deploy\Installer\pack.ps1

artifacts:
    - path: Output\Release
      name: release-binary 

    - path: '*.nupkg'
      name: nugetpackage

    - path: Output\Wox-setup.exe
      name: setup 
