version: 1.2.{build}
os: Visual Studio 2015
configuration: Release
platform: Any CPU
assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}-beta.2-$(APPVEYOR_REPO_COMMIT)'
build:
  project: Wox.sln
after_test:
- ps: >-
    .\Deploy\build-release.ps1
artifacts:
- path: 'Wox-*.zip'
  name: release_binary
  